<?xml version="1.0" encoding="UTF-8"?>
<!-- You may freely edit this file. See commented blocks below for -->
<!-- some examples of how to customize the build. -->
<!-- (If you delete it and reopen the project it will be recreated.) -->
<!-- By default, only the Clean and Build commands use this build script. -->
<!-- Commands such as Run, Debug, and Test only use this build script if -->
<!-- the Compile on Save feature is turned off for the project. -->
<!-- You can turn off the Compile on Save (or Deploy on Save) setting -->
<!-- in the project's Project Properties dialog box.-->
<project name="SWP_Project" default="default" basedir=".">
    <description>Builds, tests, and runs the project SWP_Project.</description>
    <import file="nbproject/build-impl.xml"/>
    
    <!-- Customization Targets -->
    <target name="-do-compile" depends="init, deps-jar, -pre-pre-compile, -pre-compile, -copy-manifest, -copy-persistence-xml, -copy-webdir, library-inclusion-in-archive,library-inclusion-in-manifest" if="have.sources">
        <mkdir dir="${build.web.dir}/WEB-INF/lib"/>
        <copy todir="${build.web.dir}/WEB-INF/lib">
            <fileset dir="lib" includes="*.jar" erroronmissingdir="false"/>
        </copy>
        <mkdir dir="${build.web.dir}/WEB-INF/classes"/>
        <mkdir dir="${build.dir}/classes"/>
        <javac srcdir="${src.dir}" destdir="${build.web.dir}/WEB-INF/classes" encoding="UTF-8" includeantruntime="false" debug="true" fork="true">
            <classpath>
                <fileset dir="lib" includes="*.jar" erroronmissingdir="false"/>
                <fileset dir="${build.web.dir}/WEB-INF/lib" includes="*.jar" erroronmissingdir="false"/>
                <fileset dir="${j2ee.server.home}/lib" includes="*.jar" erroronmissingdir="false"/>
            </classpath>
        </javac>
        <copy todir="${build.dir}/classes">
            <fileset dir="${build.web.dir}/WEB-INF/classes"/>
        </copy>
    </target>
</project>
