# Application Configuration
ai.dataset.path=d:/ky5/Github_SWP391/Diabetes-Prediction-System/Diabetes-Prediction-System/dataset/update/doctor_feedback.csv

# Email Configuration
mail.smtp.host=smtp.gmail.com
mail.smtp.port=587
DIABETESCARE_SMTP_USERNAME=diabetescare.system.swp@gmail.com
DIABETESCARE_SMTP_PASSWORD=xuyoblvebidpeqmr
DIABETESCARE_SMTP_FROM=diabetescare.system.swp@gmail.com

